sudo: false
language: python
python: 3.4
cache: pip
branches:
  only:
  - develop
  - uat
  - prod
env:
  global:
    - STACK_NAME=bridgeworker-$TRAVIS_BRANCH

install:
# install git-crypt
  - pushd /tmp
  - wget https://github.com/AGWA/git-crypt/archive/master.zip -O git-crypt.zip
  - unzip git-crypt.zip
  - cd git-crypt-master
  - make
  - popd
# get env vars
  - openssl aes-256-cbc -K $encrypted_d252773f4439_key -iv $encrypted_d252773f4439_iv -in git-crypt.key.enc -out git-crypt.key -d
  - /tmp/git-crypt-master/git-crypt unlock ./git-crypt.key
  - rm -rf git-crypt.key
  - source env_vars && source env_vars.secret
  - /tmp/git-crypt-master/git-crypt lock
# install aws cli
  - pip install --upgrade awscli
# configure aws cli
  - mkdir ~/.aws
  - echo -e "[default]\nregion=us-east-1" > ~/.aws/config
  - echo -e "[default]\naws_access_key_id=$AwsTravisAccessKey\naws_secret_access_key=$AwsTravisSecretAccessKey" > ~/.aws/credentials
script:
  - ./deploy_infra.sh
